CREATE PROCEDURE FOXT.SP_VALIDA_PRECARGA
	@FORMA AS VARCHAR(100)
	, @FECHAFORMA AS DATE
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

		SELECT top 1 *
		FROM FOXT.APROBACIONPRECARGA
		WHERE FORMANAME = @FORMA
		AND FECHAFORMA = @FECHAFORMA
		AND GETDATE() BETWEEN FECHAAPERTURA AND FECHACIERRE
		and Activo = 1
END
GO
