IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'APROBACIONCARGA' AND SC.name = 'FOXT')
DELETE FROM FOXT.APROBACIONCARGA
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'CONCRETEFORM' AND SC.name = 'FOXT')
DELETE FROM FOXT.CONCRETEFORM
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM9TOTALVOLUMEDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM9TOTALVOLUMEDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM9DETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM9DETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM9' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM9
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'Acumulados' AND SC.name = 'FOXT')
DELETE FROM FOXT.Acumulados
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'APROBACIONCARGA' AND SC.name = 'FOXT')
DELETE FROM FOXT.APROBACIONCARGA
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'APROBACIONPRECARGA' AND SC.name = 'FOXT')
DELETE FROM FOXT.APROBACIONPRECARGA
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORMC4' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORMC4
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORMC4NETVOLUMEDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORMC4NETVOLUMEDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORMC4TOTALVOLUMEDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORMC4TOTALVOLUMEDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM15' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM15
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM15DETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM15DETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM17DETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM17DETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM17TOTALVOLUMEDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM17TOTALVOLUMEDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM17' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM17
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM16DETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM16DETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM16' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM16
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM20' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM20
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM20DETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM20DETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM20PRODUCTIONDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM20PRODUCTIONDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM20TOTALVOLUMEDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM20TOTALVOLUMEDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM21' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM21
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM21INYECTIONDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM21INYECTIONDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM21PRODUCTIONDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM21PRODUCTIONDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM21TOTALVOLUMEDETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM21TOTALVOLUMEDETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM30' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM30
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'FORM30DETAIL' AND SC.name = 'FOXT')
DELETE FROM FOXT.FORM30DETAIL
GO
IF EXISTS (SELECT TB.name FROM SYS.TABLES TB INNER JOIN SYS.SCHEMAS SC ON TB.schema_id = SC.schema_id WHERE TB.name = 'Forma17CRDetalle' AND SC.name = 'FOXT')
DELETE FROM FOXT.Forma17CRDetalle
GO