CREATE TABLE [FOXT].[CONCRETEFORM] (
    [concreteformid]      UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_CONCRETEFORMID DEFAULT NEWID(),
    [maincampid]          NUMERIC (38)  NULL,
    [company]             VARCHAR (250) NULL,
    [contract]            VARCHAR (150) NULL,
    [battery]             VARCHAR (500) NULL,
    [tank]                VARCHAR (25)  NULL,
    [month]               NUMERIC (2)   NULL,
    [year]                NUMERIC (4)   NULL,
    [explotationmodality] VARCHAR (100) NULL,
    [annotations]         VARCHAR (512) NULL,
    [version]             NUMERIC (8)   NULL,
    [currentstate]        UNIQUEIDENTIFIER  NOT NULL,
    [generationflag]      NUMERIC (1)   NULL,
    [campid]              NUMERIC (38)  NULL,
    [pdenid]              VARCHAR (20)  NULL,
    [formid]              UNIQUEIDENTIFIER  NOT NULL,
    [generationjobid]     NUMERIC (38)  NULL,
    [iqistatus]           NUMERIC (22)  NULL,
    [usersigning]         VARCHAR (60)  NULL,
    [minrepsigning]       VARCHAR (60)  NULL,
    [formname]            VARCHAR (70)  NULL,
     CONSTRAINT [PK_CONCRETEFORMID] PRIMARY KEY CLUSTERED ([concreteformid] ASC)
);