CREATE TABLE FOXT.CUADRO1DETALLE
(
	id_cabecera UNIQUEIDENTIFIER NOT NULL,
	Forma_id UNIQUEIDENTIFIER NOT NULL,
	dias varchar(20), 
	medidaMM decimal(20,2) null,
	aforoBLS decimal(20,2) null,
	tempF decimal(20,2) null,
	factorTemp decimal(20,2) null,
	BLS60F decimal(20,2) null,
	BSW decimal(20,2) null,
	factorBSW decimal(20,2) null,
	CTSH decimal(20,2) null,
	tempAmb decimal(20,2) null,
	BLSNetos decimal(20,2) null,
	transfBLS decimal(20,2) null,
	recibidoBLS decimal(20,2) null,
	entregaBLS decimal(20,2) null,
	API60F decimal(20,2) null,
	GE decimal(20,2) null,
	netosGE decimal(20,2) null,
	salBTB decimal(20,2) null,
	fecha_creacion datetime,
	usuario_crea varchar(100),
	pdenId VARCHAR(50), 
	pden_tanque VARCHAR(50),
	pden_bateria VARCHAR(50),
	[row_created_by]          varchar(60) NULL, 
	[row_created_date]        datetime NULL, 
	[row_changed_by]          varchar(60) NULL, 
	[row_changed_date]        datetime NULL,
	[TrasRecibido] decimal(20,2) null,
	[TrasEnvio] decimal(20,2) null,
	[MovIntraRecibido] decimal(20,2) null,
	[MovIntraEnvio] decimal(20,2) null,
)