CREATE TABLE [FOXT].[FORMC4] (
    [formc4id]          UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_FORMC4_formc4id DEFAULT NEWID() CONSTRAINT PK_FORMC4 PRIMARY KEY,
    [deliverysite]      VARCHAR (100)   NULL,
    [contrato]          VARCHAR (260)   NULL,
    [contratoId]        VARCHAR (50)    NULL,
    [campoId]           VARCHAR (50)    NULL,
    [campo]             VARCHAR (260)   NULL,
    [initialstock]      NUMERIC (20, 4) NULL,
    [deliveries]        NUMERIC (20, 4) NULL,
    [vesselsdeadvolume] NUMERIC (20, 4) NULL,
    [linesdeadvolume]   NUMERIC (20, 4) NULL,
    [finalexistence]    NUMERIC (20, 4) NULL,
    [totalbalance]      NUMERIC (20, 4) NULL,
    [apigrades]         NUMERIC (8, 5)  NULL,
    [bsw]               NUMERIC (8, 5)  NULL,
    [sulfurcontent]     NUMERIC (8, 5)  NULL,
    [bloque]            VARCHAR(260) NULL,
    [bloqueId]          VARCHAR(20) NULL,
    [Formacion]         VARCHAR(260) NULL,
    [FormacionId]       VARCHAR(20) NULL,
    [FormacionSetId]    VARCHAR(20) NULL,
    [EstructuraId]      VARCHAR(20) NULL,
    [Estructura]        VARCHAR(260) NULL,
    [Yacimiento]        VARCHAR(260) NULL,
    [YacimientoId]      VARCHAR(20) NULL,
    [row_created_by]          varchar(60) NULL, 
    [row_created_date]        datetime NULL, 
    [row_changed_by]          varchar(60) NULL, 
    [row_changed_date]        datetime NULL
);