CREATE TABLE [FOXT].[FORMSTATE] (
    [formstateid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_FORMSTATE_formstateid DEFAULT NEWID(),
    [name]        VARCHAR (50) NULL,
    CONSTRAINT [PK_FORMSTATE] PRIMARY KEY CLUSTERED ([formstateid] ASC)
);

