CREATE TABLE [FOXT].[FORM] (
    [formid]     UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_FORM_formid DEFAULT NEWID(),
    [name]       VARCHAR (60) NULL,
    [formtypeid] UNIQUEIDENTIFIER NULL,
    [ismaincamp] VARCHAR (1)  DEFAULT ('N') NOT NULL,
    CONSTRAINT [PK_FORM] PRIMARY KEY CLUSTERED ([formid] ASC),
    CONSTRAINT [FK_FORM_FORMTYPE] FOREIGN KEY ([formtypeid]) REFERENCES [FOXT].[FORMTYPE] ([formtypeid])
);