CREATE TABLE [FOXT].[FORMTYPE] (
    [formtypeid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_FORMTYPE_formtypeid DEFAULT NEWID(),
    [name]       VARCHAR (30) NULL,
    CONSTRAINT [PK_FORMTYPE] PRIMARY KEY CLUSTERED ([formtypeid] ASC)
);

