CREATE TABLE [FOXT].[FORMC7DETAIL]
(
	  [formc7id]		   UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_FORMC7DETAIL_formc7id DEFAULT NEWID(),
	  [formid]             UNIQUEIDENTIFIER NOT NULL,
	  [fieldid]            numeric(38),
	  [oilproduction]      numeric(20,4),
	  [gasproduction]      numeric(20,4),
	  [endwells]           numeric(5),
	  [activewells]        numeric(5),
	  [inactivewells]      numeric(5),
	  [abandonedwells]     numeric(5),
	  [unfinishedwells]    numeric(5),
	  [injectorwells]      numeric(5),
	  [oilproductionwell]  numeric(20,4),
	  [gasproductionwells] numeric(5),
	  [pden_id]			   VARCHAR(260),
	  [row_created_by]          varchar(60) NULL, 
	  [row_created_date]        datetime NULL, 
	  [row_changed_by]          varchar(60) NULL, 
      [row_changed_date]        datetime NULL,
	  [pozosProductoresActivosLevantamientoArtificial] VARCHAR(150),
	  [pozosProductoresActivosFlujoNatural] VARCHAR(150),
	  [pozosProductoresInactivosCerradoAltaRelacionAguaPetroleo] VARCHAR(150),
	  [pozosProductoresInactivosCerradoTemporalmente] VARCHAR(150),
	  [pozosTaponadosSecos] VARCHAR(150),
	  [pozosSuspendidosTemporalmente] VARCHAR(150),
	  [pozosSinTerminar] VARCHAR(150), 
    [pozosTaponadosInyectores] DECIMAL(20, 4) NULL, 
    [pozosTaponadosInyectoresGas] DECIMAL(20, 4) NULL, 
    [pozosTaponadosInyectoresAire] DECIMAL(20, 4) NULL
)
