CREATE TABLE [FOXT].[FORM30DETAIL] (
    [form30detail]             UNIQUEIDENTIFIER NOT NULL CONSTRAINT DK_FORM30DETAIL_form30detail DEFAULT NEWID(),
    [formid]                   UNIQUEIDENTIFIER    NULL,
    [campo]                VARCHAR (50)    NULL,
    [gasFormacionKPC]               NUMERIC (20, 4)    NULL,
    [contenidoPropano]                 NUMERIC (20, 4)     NULL,
    [contenidoButano]       NUMERIC (20, 4) NULL,
    [contenidoGasolinaNatural] NUMERIC (20, 4) NULL,
    [gasFormacionProcesado]       NUMERIC (20, 4) NULL,
    [consumoEnCampo]               NUMERIC (20, 4) NULL,
    [generacionElectrica]                NUMERIC (20, 4) NULL,
    [otros]              NUMERIC (20, 4) NULL,
    [quemadoAire]    NUMERIC (20, 4) NULL,
    [usadoBombeoNeumatico]             NUMERIC (20, 4) NULL,
    [inyectadoYacimiento]      NUMERIC (20, 4) NULL,
    [productosObtenidosGasTotalGasProcesadoPlanta]    NUMERIC (20, 4) NULL,
    [productosObtenidosGasPropano]            NUMERIC (20, 4) NULL,
    [productosObtenidosGasButano]                NUMERIC (20, 4) NULL,
    [productosObtenidosGasGasolina]       NUMERIC (20, 4) NULL,
    [productosObtenidosGasTransformadoGasolinaNaturalPropanosButanos]              NUMERIC (20, 4) NULL, 
    [productosGasProcesadoConsumoEnCampo] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoGasoductosUrbanos] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoGeneracionElectrica] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoOtros] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoQuemadoAire] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoUsadoBombeoNeumatico] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoInyectadoYacimiento] NUMERIC(20, 4) NULL, 
    [productosGasProcesadoObservaciones] VARCHAR(2000) NULL, 
    [REAL_TP] VARCHAR(20) NULL,  
        [REAL] VARCHAR(20) NULL, 
        [REAL_BAS] VARCHAR(20) NULL, 
        [REAL_INC] VARCHAR(20) NULL, 
        [GAS_PROCESADO_TP] VARCHAR(20) NULL, 
        [GAS_QUEMADO_TP] VARCHAR(20) NULL, 
        [GLP_TP] VARCHAR(20) NULL, 
        [GLP] VARCHAR(20) NULL, 
        [PROPANO_TP] VARCHAR(20) NULL, 
        [BUTANO_TP] VARCHAR(20) NULL, 
        [GASOLINA_TP] VARCHAR(20) NULL, 
        [APIASOL_TP] VARCHAR(20) NULL, 
        [APIASOL] VARCHAR(20) NULL, 
        [CONDENSADO_TP] VARCHAR(20) NULL, 
        [CONDENSADO] VARCHAR(20) NULL, 
        [CONSUMOS_TP] VARCHAR(20) NULL, 
        [GASODUCTOS_URBANOS_TP] VARCHAR(20) NULL, 
        [GASODUCTOS_URBANOS] VARCHAR(20) NULL, 
        [GENERACION_ELECTRICA_TP] VARCHAR(20) NULL, 
        [OTRAS_VENTAS_TP] VARCHAR(20) NULL, 
        [GAS_TRANFERENCIA_TP] VARCHAR(20) NULL, 
        [GAS_TRANFERENCIA] VARCHAR(20) NULL, 
        [GAS_NEUMATICO_TP] VARCHAR(20) NULL, 
        [GAS_INYECTADO_TP] VARCHAR(20) NULL, 
        [TOTAL_PROC_PLANTA_TP] VARCHAR(20) NULL, 
        [GP_TRATOTAL_PROC_PLANTA_TP] VARCHAR(20) NULL, 
        [GP_TRATOTAL_PROC_PLANTA] VARCHAR(20) NULL, 
        [GP_CONSUMOS_TP] VARCHAR(20) NULL, 
        [GP_GASODUCTOS_URBANOS_TP] VARCHAR(20) NULL, 
        [GP_GENERACION_ELECTRICA_TP] VARCHAR(20) NULL, 
        [GP_OTRAS_VENTAS_TP] VARCHAR(20) NULL, 
        [GP_NEUMATICO_TP] VARCHAR(20) NULL, 
        [GP_QUEMADO_TP] VARCHAR(20) NULL, 
        [GP_INYECTADO_TP] VARCHAR(20) NULL, 
        [REPRESENTA_OPER] VARCHAR(20) NULL, 
        [REPRESENTA_ANH] VARCHAR(20) NULL, 
        [IDFORMA] VARCHAR(20) NULL, 
    [campo_id] VARCHAR(10) NULL,
    [pden_id] VARCHAR(50) NULL,
    [volume_date] VARCHAR(10) NULL,
    [row_created_by]          varchar(60) NULL, 
    [row_created_date]        datetime NULL, 
    [row_changed_by]          varchar(60) NULL, 
    [row_changed_date]        datetime NULL
);

