CREATE TABLE [FOXT].[HOMOLOGACIONES]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CAMPO] VARCHAR(50),
	[POZO_FORMA] VARCHAR(150),
	[ID_POZO_YAC] VARCHAR(150),
	[NOMBRE_POZO_YAC] VARCHAR(150),
	[POZO] VARCHAR(150),
	[UWI] VARCHAR(150),

)
